cask_args appdir: '/Applications'

brew 'atuin'
brew 'imagemagick'
brew 'spaceman-diff'
brew 'wget'
brew 'yt-dlp'
brew 'fontconfig'
brew 'volta'
brew 'bitwarden-cli'
brew 'tmux'
brew 'uv'
brew 'gh'
tap 'atlassian/homebrew-acli'
brew 'acli'
brew 'zoxide'
brew 'fzf'

cask 'bitwarden'
cask 'claude-code'
cask 'conductor'
cask 'ghostty'
cask 'handbrake-app'
cask 'iina'
cask 'quicklook-video'
cask 'telegram'
cask 'transmission'
#cask 'raycast'
cask 'whatsapp'
cask 'vlc'
cask 'zed'
cask 'obsidian'
cask 'font-fira-code-nerd-font'
cask 'claude'
cask 'lm-studio'
